### ISSUE TITLE
Credentials stored in file

### ISSUE THREAD

**Issue by Securitybits-io** [itsumeet/login-signup-page#1]
controller/loginController.js
I was wondering if it was intentional to store the MongoDB credentials in this file?

**Comment by itsumeet** [comment]
no it wasn't i will remove it asap

**Comment by Securitybits-io** [comment]
In this early stage, i would recommend deleting the repo and recreate it in order to get rid of the commit history! otherwiose it'll still be in the log.!

**Comment by itsumeet** [comment]
sure will do thanks
